-- Ne-Yo Ticket Sales — PostgreSQL schema
-- Records are intentionally NOT auto-deleted. Sales close automatically
-- after the event window, but orders/payments/tickets persist so you can
-- reconcile, refund, and resolve disputes after the window ends.

CREATE TABLE IF NOT EXISTS event_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name VARCHAR(255) NOT NULL,
  venue VARCHAR(255) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  sales_open_at TIMESTAMP NOT NULL,
  sales_close_at TIMESTAMP NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed'))
);

CREATE TABLE IF NOT EXISTS ticket_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  total_quantity INTEGER NOT NULL,
  reserved_quantity INTEGER NOT NULL DEFAULT 0,
  sold_quantity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY,
  customer_name VARCHAR(150) NOT NULL,
  customer_phone VARCHAR(20) NOT NULL,
  customer_email VARCHAR(150) NOT NULL,
  ticket_type_id INTEGER NOT NULL REFERENCES ticket_types(id),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  total_amount NUMERIC(10,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'reserved'
    CHECK (status IN ('reserved', 'pending_payment', 'paid', 'failed', 'expired')),
  reserved_until TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  method VARCHAR(10) NOT NULL CHECK (method IN ('mpesa', 'card', 'bank')),
  provider_reference VARCHAR(150),
  checkout_request_id VARCHAR(150),
  amount NUMERIC(10,2) NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'initiated'
    CHECK (status IN ('initiated', 'pending', 'success', 'failed')),
  raw_callback JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  ticket_code VARCHAR(40) UNIQUE NOT NULL,
  qr_data TEXT,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  checked_in BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL
);

-- Seed example data. These INSERTs only run when the tables are empty.
INSERT INTO event_settings (event_name, venue, event_date, sales_open_at, sales_close_at, status)
SELECT 'Ne-Yo Live', 'TBD Venue, Nairobi', TIMESTAMP '2026-09-20 19:00:00',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '8 hours', 'open'
WHERE NOT EXISTS (SELECT 1 FROM event_settings);

INSERT INTO ticket_types (name, price, total_quantity)
SELECT * FROM (VALUES
  ('Regular', 3000.00::NUMERIC, 500),
  ('VIP', 8000.00::NUMERIC, 150),
  ('VVIP', 15000.00::NUMERIC, 50)
) AS seed(name, price, total_quantity)
WHERE NOT EXISTS (SELECT 1 FROM ticket_types);
